### PR TITLE
Update ME81H

### PR DESCRIPTION
**Pull request by g6094199**
1st step for deeper dp info

### CODE REVIEW

**Comment by nikvostro** [comment]
Hi!
You've shared the template and added Tuya commands but there are no Tyua GPIOs (Tuya Rx/Tx) are defined in your template...
Could you please give a comment on this?
What about display and reading thermosensor value?

Nikolay

**Comment by blakadder** [comment]
module 54 sets the tuya rx and tx pins

**Comment by nikvostro** [comment]
> module 54 sets the tuya rx and tx pins

Thank you! Missed that. https://tasmota.github.io/docs/TuyaMCU-Devices/#config

**Comment by g6094199** [comment]
its just the beginning. there are many dlps missing which i have to get straight first.

[board rev. 1.4](https://user-images.githubusercontent.com/1146409/187263106-5909335d-d984-4c59-9668-6619a9a6f58e.jpg)

**Pull request merged**
