### PR TITLE
MS-105 Dimmer Unsupported

### PR DESCRIPTION
**Pull request by Xeyame**
Looks very similar, purchased from the link but is a fake clone.

### CODE REVIEW

**Comment by blakadder** [comment]
The images you linked to clearly show an ESP module TYWE2S which is supported

**Comment by Xeyame** [comment]
Well i feel very dumb now lol, i didn't notice the marking on this one being different from a relay board that i got from the same seller, with a module named "WA2", (but that relay was a way different one than the one i acutally bought, and i think is not esp.)
afbeelding

**Comment by blakadder** [comment]
WA2 is indeed unsupported

**Comment by blakadder** [comment]
WA2 is indeed a module with a nonESP chip

**Comment by Xeyame** [comment]
Yea. Waiting for the dispute from aliexpress, as i bought a way different model. I'm curious what's under the tin so ill look into that soon, and i might be able to fit an esp-01 into the enclosure instead :)

**Comment by corbolais** [comment]
> WA2 is indeed a module with a nonESP chip. by the looks of it this might be the one in the unsupported list

[This site](https://smartpets.en.made-in-china.com/product/ESzJbYnKVcRg/China-Esp-8285-Tuya-Tywe2s-Smart-WiFi-Module-Develop-Wireless-Networking-Intelligent-Module.html) states, the `TYWE2S` module is a "ESP 8285 TUYA TYWE2S" module. In the description, they then call it a "ESP8266EX". Well, pick your favourite one. Least common denominator would be, it's an ESP[82XX]. So, it *is not* a "nonESP". But the module looks somewhat like the `WA2` and the page popped up searching for `WA2`, so why should there be a nonESP under the hood (granted, the looks may very well decieving)? Any sources confirming this statement?

This `WA2` module is sitting inside those [smart switches](https://www.ebay.de/itm/2-4G-WiFi-Smart-Light-Switch-DIY-Circuit-Breaker-Module-Supports-for-Voice-Box/254456260792).

**Comment by blakadder** [comment]
was there a point to be made there?

**Comment by corbolais** [comment]
Well not any more. Technically, it will help users grasp the situation as it provides pointers and clarification.

**Comment by Xeyame** [comment]
Might help random people lost on google yea

**Comment by blakadder** [comment]
by stating WA2 is an esp based module when its clearly not?

**Comment by Xeyame** [comment]
Oh yea sorry i was kind of lost in the wording of that comment, Yea WA2 is BK7231U and not anything ESP. However the link might help.

**Pull request merged**
