### PR TITLE
Update ghome_EP2-A

### PR DESCRIPTION
**Pull request by rovo89**
Switch Led_i and LedLinki. After the change, the power status is shown with the green LED and the WiFi status with the blue LED.

### CODE REVIEW

**Comment by barbudor** [comment]
As far as I understand, this change is not functional but a personal preference

I suggest that you modify your PR to add this template in the text and explaining the difference between both so user can choose which one they prefer

**Comment by rovo89** [comment]
I can do that if you prefer, although I always associate the colors this way.
Do you have an example how this can be achieved, especially with the explanatory text?

**Comment by barbudor** [comment]
@rovo89 you can add text below
Skip one line and you can add mark down formated text

See that one
https://github.com/blakadder/templates/blob/master/_templates/rocket_R4A4

**Comment by rovo89** [comment]
I took some inspiration here: https://github.com/blakadder/templates/blob/master/_templates/blitzwolf_SHP6

**Comment by rodajc** [comment]
With the modification as proposed by @rovo89 the green LED indicates the power state which is definitely more consistent with other devices and with the original firmware.

When I submitted the first version of the template for this device I copied it from the old Nous A1 as recommended by... @barbudor.

I didn't pay much attention to the LEDs as I didn't know what to expect. I was happy it was switching on and off and submitted the template after changing only the NAME.

Now @rovo89 proposes an enhancement I think we should publish as the template to use with this device.

**Pull request merged**
