### PR TITLE
Do not wrap gpio table content

### PR DESCRIPTION
**Pull request by ThomDietrich**
Avoid wrap on https://templates.blakadder.com/blitzwolf_SHP5.html

### CODE REVIEW

**Comment by blakadder** [comment]
that's a very blunt "solution"

**Comment by ThomDietrich** [comment]
what's blunt about it? Neither the GPIO names nor the component descriptions will exceed certain length, hence this is totally fine.

What's not so cool about the PR is that it would affect all tables, which might not be desired. You need to add an `id` to the table which is currently missing. If you were not so quick to close the pull request I could have added that change 🤷‍♂

**Comment by blakadder** [comment]
affecting all tables is the blunt part of it. 

what would a table id accomplish there?

**Comment by ThomDietrich** [comment]
https://www.w3schools.com/html/html_id.asp

**Comment by blakadder** [comment]
wow! didn't know that... thanks

**Pull request closed without merging**
