### PR TITLE
Update rjwf-02a

### PR DESCRIPTION
**Pull request by sfromis**
Better include required config details in the template

### CODE REVIEW

**Comment by blakadder** [comment]
Does that work on old templates?

**Comment by sfromis** [comment]
Looks like the answer is yes. On current dev Tasmota, I did a test with the amended template on that dimmer, after setting DimmerRange differently. The console showed a message about the template being converted, and after the restart, the DimmerRange was reset according to the template.

**Comment by sfromis** [comment]
More generally, when fixing small irregularities i templates, I've assumed that it is not preferred to convert them to new component numbers. While it would be easy to do, it does reduce compatibility with old binaries. While probably not much of a problem, my stance became to not change more than I came for. I'm open to suggestions about changing this stance :-)

**Comment by blakadder** [comment]
That's fine, just wanted to check whether the cmnd key works even if the old template format is used

**Pull request merged**
