### PR TITLE
Add cross-reference

### PR DESCRIPTION
**Pull request by andySFRD**
The two devices are apparently identical

### CODE REVIEW

**Comment by blakadder** [comment]
That's a weird definition of identical when the images show they clearly aren't

**Comment by andySFRD** [comment]
the inside is the same and also the case looks identical, except the print...

**Comment by andySFRD** [comment]
pictures of the inside of DDS238-2 https://github.com/krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota
pictures of the inside of ktem06 https://tasmota.github.io/docs/TuyaMCU-Devices/#ketotek-ktem06

maybe it is useful to add a link from https://templates.blakadder.com/hiking_DDS238-2.html to https://github.com/krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota as well.

**Comment by andySFRD** [comment]
DDS238-2 is identical to KTEM06, see https://github.com/krikk/Hiking-DDS238-2-WIFI-Din-Rail-Energy-Meter-flashing-Tasmota/issues/27#issuecomment-1741953417

**Pull request closed without merging**
