### PR TITLE
Sonoff d1

### PR DESCRIPTION
**Pull request by kumy**
Please find some new devices and enhanced pictures for other models

### CODE REVIEW

**Comment by kumy** [comment]
There is only one load output available to a standard user. do you mean we should also map Tx Rx as `user`? I ve attached pcb pictures may you cross check available feature please.

**Comment by kumy** [comment]
+buzzer +led?
How should the rf receiver be mapped?

**Comment by blakadder** [comment]
I don't know, I don't own the device. If I did I'd already post a template

**Comment by kumy** [comment]
Didn't you closed it by mistake? ;)

**Comment by blakadder** [comment]
Everything is added directly

**Pull request closed without merging**
