### PR TITLE
Update WF-CS01_EU

### PR DESCRIPTION
**Pull request by mijnmodelbaan**
I've added some description and some pictures on how to flash it and set it up.
Please move the pictures to GitHub; they will be removed from my flickr account in due time.

### CODE REVIEW

**Comment by blakadder** [comment]
You can host the pictures in your github

**Comment by mijnmodelbaan** [comment]
Would like to host pictures on my github, but can't find exactly how (it's
all new to me).
Checked out the 'Kingart Touch Dimmer' page on how to insert images, but
need more info.
The help pages talk about a toolbar with insert button, but I don't see a
toolbar (in chrome).
I'll find it out somehow and change the page again.

**Comment by blakadder** [comment]
Just open an issue in on of your github repos... or use the issue tracker here, paste the image in Write box and github will automagically produce a permanent link you can use

**Comment by mijnmodelbaan** [comment]
Thanks, working like a charm!

**Pull request merged**
