### PR TITLE
Update lonsonho_X803A

### PR DESCRIPTION
**Pull request by ovidiu-vas**
Fix GPIO13; add relay for toggling background light.

### CODE REVIEW

**Comment by blakadder** [comment]
why do you have relay4i ???

**Comment by ovidiu-vas** [comment]
That's a personal preference. I prefer to start with the background lights off but it can be set to Relay4 (24) to turn them on by default. I wrote this in the commit below the template code.

**Comment by blakadder** [comment]
your personal preference is wrong because that device doesn't have a fourth relay

**Comment by ovidiu-vas** [comment]
Please read the comment added in the commit:

**Relay 4 toggles the green LEDs on all buttons. To turn on the green LEDs from the start set Relay 4 to "Relay4 (24)".**

The 4th relay is not an actual physical relay. It's set as a relay so that you can see it in Tasmota as a toggle and switch on/off  the background LEDs.

**Comment by blakadder** [comment]
Yes I understood that part. And it is still wrong. The fact it can be done and it works for you doesn't mean it should be done and it works for everyone else.

**Comment by ovidiu-vas** [comment]
What do you mean? It works for everyone. The current template is bugged and forces the first relay to inverted because of how the second relay is done.

**Comment by blakadder** [comment]
Then please submit a template without imaginary relays

**Pull request closed without merging**
