### PR TITLE
Adding US Smart Plug ZONKO ZK-R

### PR DESCRIPTION
**Pull request by hostirosti**

### CODE REVIEW

**Comment by blakadder** [comment]
you're missing a link to the product

**Comment by hostirosti** [comment]
Added one.

**Comment by hostirosti** [comment]
Closed without merge and reason?

**Comment by hostirosti** [comment]
It is the same as https://templates.blakadder.com/avatar_AWP02L-N.html and https://templates.blakadder.com/hugoai_awp02l-n.html under different brand name.

**Comment by blakadder** [comment]
i asked for a link to the product, you failed to produce one

**Comment by hostirosti** [comment]
Can you specify what qualifies for a valid link?

To provide some context, I've searched and the product doesn't appear to be sold anymore under that name. However some folks might have it in their possession and being able to lookup a template by product name is easier than picture matching from existing templates. Just my 2ct.

FWIW, I added this link in my 2nd commit to this PR.
https://reviewmeta.com/amazon/B079FS53MW

**Comment by hostirosti** [comment]
@blakadder I and many others appreciate the work you do to keep up that templates repository. However, I still don't understand what is missing and I sense a bit of hostility in your response without knowing where this is coming from.

**Pull request closed without merging**
