### PR TITLE
Update moes-MS-105-1

### PR DESCRIPTION
**Pull request by apc300**

### CODE REVIEW

**Comment by blakadder** [comment]
You're changing the entire template which means its a new device

**Comment by apc300** [comment]
hi blakadder
would you like me to provide you with photos of the packaging and instructions for MoesHouse MS-105 Wifi Dimmer, bought from MoesHouse aliexpress?
i believe this is the listing for the correct device
thanks

**Comment by blakadder** [comment]
yes but there's also the previous device which you're just deleting

**Comment by apc300** [comment]
There is already a page for the previous device version https://github.com/blakadder/templates/blob/master/_templates/qs-wifi_D01_dimmer

**Comment by blakadder** [comment]
and your point is? just submit a new template or don't

**Comment by apc300** [comment]
could you elaborate please, i'm unsure why the device is not the same as the current template

**Pull request closed without merging**
