### PR TITLE
Update lsc_smart_connect_power_plug

### PR DESCRIPTION
**Pull request by mroelandts**
The new power plugs of LSC do not contains a ESP anymore!

### CODE REVIEW

**Comment by Pacerino** [comment]
Hey,

I recently bought LSC plugs and after opening them I was able to flash them successfully with Tasmota using ESPTool!
My LSC plugs have no screws, you had to "lever them out".
My version number: 970760.1 #2

photo_2020-09-24_22-52-55

**Comment by mroelandts** [comment]
I was told that mine did not contain a ESP chip
https://github.com/ct-Open-Source/tuya-convert/issues/729
My version number is: 970962
120187477_276559960452207_3677718485447578292_n

**Comment by Pacerino** [comment]
Then the information on the page is wrong! On the website under Unsupportable Devices you can find version number: 970760.1 v2.0 and you have a completely different one! @blakadder

**Comment by mroelandts** [comment]
You're correct, the info needs to be updated for the model numbers.
I've read on this [forum](https://gathering.tweakers.net/forum/list_message/63909938#63909938) (not English but dutch) the 970761 v1.0 also does not have an ESP but the Tuya WB2S module. (this info can be added as well)

**Pull request merged**
